version: '3.7'
services:
  
  #VPN Service
  softether:
    image: mrtshoot/softether:5.1.9
    container_name: softether
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      # - 53:53
      - 4443:443
      - 992:992
      - 27030:1194/udp
      - 5555:5555
      - 510:500/udp
      - 4510:4500/udp
      - 1701:1701/udp
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./se_data:/mnt"
      - "./se_log:/root/server_log"
      - "./se_packetlog:/root/packet_log"
      - "./se_securitylog:/root/security_log"
  
  #Proxy Service
  squid:
    image: mrtshoot/squid-proxy:0.1
    container_name: squid
    ports:
      - 8443:3128
    env_file:
      - squid.env
    restart: unless-stopped
