version: '3'

services:
  softether:
    image: toprock/softether:5.01.9672
    name: softether
    container_name: softether
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    restart: always
    ports:
      - 53:53
      - 4443:443
      - 992:992
      - 27030:1194/udp
      - 5555:5555
      - 510:500/udp
      - 4510:4500/udp
      - 1701:1701/udp
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./softether_data:/mnt"
      - "./softether_log:/root/server_log"
      - "./softether_packetlog:/root/packet_log"
      - "./softether_securitylog:/root/security_log"
  squid:
    image: yegor256/squid-proxy:0.1
    name: squid
    container_name: squid
    ports:
      - 8443:3128
    environment:
      - USERNAME=mrtshoot
      - PASSWORD=mrtshoothdf4Gedsadd 
    restart: unless-stopped
    volumes:
      - "./squid.conf:/etc/squid/squid.conf"
